// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2FDdVs8ecijkSToZBRhBxXzWa_wIPHo',
    appId: '1:864450310750:web:b73e8ba0e5d6667b603acf',
    messagingSenderId: '864450310750',
    projectId: 'fir-example-30b54',
    authDomain: 'fir-example-30b54.firebaseapp.com',
    databaseURL: 'https://fir-example-30b54-default-rtdb.firebaseio.com',
    storageBucket: 'fir-example-30b54.appspot.com',
    measurementId: 'G-P0CRG7KHTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUo5ijCOy3YBDC3A7BX8rTX8KQ8rHhQQ',
    appId: '1:864450310750:android:0279b5d1d0adfbc1603acf',
    messagingSenderId: '864450310750',
    projectId: 'fir-example-30b54',
    databaseURL: 'https://fir-example-30b54-default-rtdb.firebaseio.com',
    storageBucket: 'fir-example-30b54.appspot.com',
  );
}
