// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBynfqET8Sl6AVng94R6Oq6lYQp_-XISLQ',
    appId: '1:486093919888:web:ac687c3f09ecb485e72a15',
    messagingSenderId: '486093919888',
    projectId: 'iotx-e71c4',
    authDomain: 'iotx-e71c4.firebaseapp.com',
    databaseURL: 'https://iotx-e71c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotx-e71c4.appspot.com',
    measurementId: 'G-9J44TC92FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiA-QSKVuyh82NBEbfSHmIxPIYI3CN9pY',
    appId: '1:486093919888:android:ae298644f8c591f1e72a15',
    messagingSenderId: '486093919888',
    projectId: 'iotx-e71c4',
    databaseURL: 'https://iotx-e71c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotx-e71c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmLnVlB4twWP5fV6aGTLPKGfm1z09f9BY',
    appId: '1:486093919888:ios:4526ccdcf6aefdc0e72a15',
    messagingSenderId: '486093919888',
    projectId: 'iotx-e71c4',
    databaseURL: 'https://iotx-e71c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotx-e71c4.appspot.com',
    iosBundleId: 'com.example.kiemtralan2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmLnVlB4twWP5fV6aGTLPKGfm1z09f9BY',
    appId: '1:486093919888:ios:4526ccdcf6aefdc0e72a15',
    messagingSenderId: '486093919888',
    projectId: 'iotx-e71c4',
    databaseURL: 'https://iotx-e71c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotx-e71c4.appspot.com',
    iosBundleId: 'com.example.kiemtralan2',
  );
}
